project/app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify, session
import os
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.utils import secure_filename
from project.utils.auth import authenticate, create_user, validate_email, update_password
from project.extensions.dependencies import db
from project.models.users import ProfilePicture
from project.models.products import Product, ProductVariation, Cart, CartItem, Order, OrderItem, ShippingAddress, Payment, Color, Brand, Size
from functools import reduce
import requests

app = Blueprint('app', __name__, template_folder='templates', static_folder='static', static_url_path='/')

PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')
UPLOADS_FOLDER = os.path.join(app.static_folder, 'app/uploads/')
STATIC_URL_PATH = f'/{app.name}/uploads/'
if not os.path.exists(UPLOADS_FOLDER): os.mkdir(UPLOADS_FOLDER)
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@app.route('/')
def index():
    items = []
    if session.get('cart'):
        items = session.get('cart')
        session.pop('cart')
    return render_template('app/index.html', init_cart=items)

@app.route('/signin', methods=['GET', 'POST'])
def signin():

    if request.method == 'GET':
        if current_user.is_authenticated:
            return redirect(url_for('app.index'))
        return render_template('app/signin.html')
    elif request.method == 'POST':

        email = request.form.get('email')
        password = request.form.get('password')
        remember = True if request.form.get('remember-me') else False
        user, error = authenticate(email=email, password=password)
        flash(error)

        if user is not None:
            cart = Cart.get_or_create(user)
            items = [{
                'id': item.id,
                'product_id': item.product_variation.product.id,
                'variation_id': item.variation_id,
                'name': item.product_variation.product.name,
                'price': round(float(item.product_variation.price), 2),
                'size': item.product_variation.size,
                'color': item.product_variation.color,
                'quantity': item.quantity,
                'image': item.product_variation.images[0].image_url,
                'total': round(float(item.product_variation.price * item.quantity), 2)
            } for item in cart.items]
            session['cart'] = items

            login_user(user=user, remember=remember)
            return redirect(url_for('app.index'))
        return render_template('app/signin.html')

@app.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'GET':
        return render_template('app/signup.html')
    elif request.method == 'POST':
        first_name = request.form.get('fullname').split()[0] if len(request.form.get('fullname').split()) > 0 else ''
        last_name = request.form.get('fullname').split()[1] if len(request.form.get('fullname').split()) > 1 else ''
        email = request.form.get('email')
        password = request.form.get('password')
        confirm_password = request.form.get('cpassword')
        terms = True if request.form.get('terms') else False

        if terms:
            print('passed')
            user, error = create_user(first_name=first_name, last_name=last_name, email=email, password=password, confirm_password=confirm_password)
            flash(error)
            if user is not None:
                login_user(user=user)
                return redirect(url_for('app.index'))
        else:
            flash({'terms': 'You must agree to the terms and conditions'})


        return render_template('app/signup.html')

@app.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    if request.method == 'POST':
        data = request.form
        print(data.get('fname'))
        if data.get('action') == 'picture-form':
            file = request.files.get('profile-picture')
            if file.filename == '':
                flash({'profile_picture':'No selected file', 'cat': 'danger'})
                return render_template('app/settings.html')
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file_path = os.path.join(UPLOADS_FOLDER, filename)
                relative_url = STATIC_URL_PATH + filename
                file.save(file_path)

                # Clear all previous profile pictures and save new one
                if current_user.profile_picture:
                    current_user.profile_picture.clear()
                pfp = ProfilePicture(url=relative_url, user=current_user)
                db.session.add(pfp)
                db.session.commit()
                flash({'profile_picture':'Profile picture updated successfully!', 'cat': 'success'})
                return render_template('app/settings.html')
        elif data.get('action') == 'personal-info-form':
            print('triggered')
            if data.get('fname'):
                current_user.first_name = str(data.get('fname'))
                db.session.commit()
                flash({'f_name':'First name updated successfully', 'cat': 'success'})
            if data.get('lname'):
                current_user.last_name = str(data.get('lname'))
                db.session.commit()
                flash({'l_name':'Last name updated successfully', 'cat': 'success'})
            if data.get('phone'):
                current_user.phone = int(data.get('phone'))
                db.session.commit()
                flash({'phone':'Phone number updated successfully', 'cat': 'success'})
            if data.get('email'):
                email, error = validate_email(email=str(data.get('email')))
                if email is not None:
                    current_user.email = email
                    db.session.commit()
                    flash({'email':'Email address updated successfully', 'cat': 'success'})
                else:
                    flash({'email':error, 'cat': 'danger'})
        elif data.get('action') == 'security-info-form':
            if current_user.check_password(data.get('oldpassword')):
                response = update_password(user=current_user, password=data.get('newpassword'), confirm_password=data.get('confirmpassword'))
                flash(response)
            else:
                flash({'oldpassword':'Invalid password for current user', 'cat': 'danger'})

    return render_template('app/settings.html')

@app.route('/update_profile_image', methods=['PUT'])
def update_profile_image():
    if request.method == 'PUT':
        data = request.form
        if data.get('action') == 'picture-form':
            file = request.files.get('profile-picture')
            print(file)
            if file.filename == '':
                jsonify({'status': 'error', 'message': 'No selected file'})
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file_path = os.path.join(UPLOADS_FOLDER, f'profileimg/{filename}')
                relative_url = STATIC_URL_PATH + f'profileimg/{filename}'
                file.save(file_path)

                # Clear all previous profile pictures and save new one
                if current_user.profile_picture:
                    current_user.profile_picture.clear()
                pfp = ProfilePicture(url=relative_url, user=current_user)
                db.session.add(pfp)
                db.session.commit()
                return jsonify({'status': 'success', 'image_url': current_user.get_profile_picture_url()})

@app.route('/signout')
@login_required
def signout():
    logout_user()
    return redirect(url_for('app.index'))

@app.route('/account')
def account():
    all_orders = []
    for order in current_user.orders:
        if len(all_orders) < 3:
            all_orders.append({
                'id': order.id,
                'date': order.created_at.strftime('%B %d, %Y'),
                'status': order.status,
                'total': order.total_price,
                'no_of_items': reduce(lambda total, item: total + item, [items.quantity for items in order.items])
            })

    return render_template('app/account.html', orders=all_orders)

@app.route('/billing')
def billing():
    return render_template('app/billing.html')

@app.route('/payment')
def payment():
    all_payments = []
    for payment in current_user.payments:
        all_payments.append({
            'order_id': payment.order_id,
            'transaction_id': payment.transaction_id,
            'date': payment.created_at.strftime('%B %d, %Y'),
            'payment_status': payment.payment_status,
            'amount_paid': payment.amount_paid
        })
    return render_template('app/payment.html', payments=all_payments)

@app.route('/orders')
def complete_checkout():
    return jsonify({'order': 'success'})

@app.route('/social')
def social():
    return render_template('app/social.html')

@app.route('/shop')
def shop():
    # Get the filter values from the request args
    name_filter = request.args.get('s', '')
    color_filter = request.args.get('color', '')
    brand_filter = request.args.get('brand', '')
    size_filter = request.args.get('size', '')

    # Get page from query params, default to 1
    page = request.args.get('page', 1, type=int)
    per_page = 2  # Number of products per page

    # Start with a base query
    query = Product.query

    # Join product variations if color, size filters or brand filters
    if color_filter or size_filter or brand_filter:
        query = query.join(ProductVariation)

    # Apply filters if any
    if color_filter:
        query = query.join(Color).filter(Color._color.ilike(color_filter))

project/app/templates/app/billing.html
{% extends 'app/account.html' %}
{% block content2 %}
<div class="w-full md:px-3 mt-6 md:mt-0">
    <div class="p-6 rounded-md shadow dark:shadow-gray-800 bg-white dark:bg-slate-900">
        <h6 class="text-slate-400 mb-0">The following addresses will be used on the checkout page by default.</h6>
        <div class="grid lg:grid-cols-2 grid-cols-1 gap-6 mt-6">
            <div class="">
                <div class="flex items-center mb-4 justify-between">
                    <h5 class="text-xl font-medium">Billing Address:</h5>
                    <a href="user-billing.html#" class="text-primary text-lg"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit size-4"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg></a>
                </div>
                <div class="pt-4 border-t border-gray-100 dark:border-gray-700">
                    <p class="text-lg font-medium mb-2">Jesus Zamora</p>

                    <div class="">
                        <div class="flex">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map-pin size-4 me-2 mt-1"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
                            <p class="text-slate-400">C/54 Northwest Freeway, Suite 558, <br> Houston, USA 485</p>
                        </div>

                        <div class="flex mt-1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone size-4 me-2 mt-1"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
                            <p class="text-slate-400">+123 897 5468</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="">
                <div class="flex items-center mb-4 justify-between">
                    <h5 class="text-xl font-medium">Shipping Address:</h5>
                    <a href="" class="text-primary text-lg"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit size-4"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg></a>
                </div>
                <div class="pt-4 border-t border-gray-100 dark:border-gray-700">
                    <p class="text-lg font-medium mb-2">Jesus Zamora</p>

                    <div class="">
                        <div class="flex">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map-pin size-4 me-2 mt-1"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
                            <p class="text-slate-400">C/54 Northwest Freeway, Suite 558, <br> Houston, USA 485</p>
                        </div>

                        <div class="flex mt-1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone size-4 me-2 mt-1"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
                            <p class="text-slate-400">+123 897 5468</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project/app/templates/app/cart.html
{% extends 'app/base.html' %}
{% block content %}
<section class="pt-24 w-full h-full">
    <section class="relative table w-full py-16 lg:py-20 md:pt-28 bg-gray-200 dark:bg-slate-800">
        <div class="container mx-auto relative px-3">
            <div class="grid grid-cols-1 mt-8">
                <h3 class="text-3xl leading-normal font-semibold">Fashion</h3>
            </div><!--end grid-->

            <div class="relative mt-3">
                <div class="tracking-[0.5px] mb-0 inline-block">
                    <div
                        class="inline-block uppercase text-[13px] font-bold duration-300 ease-in-out hover:text-orange-500">
                        <a href="">Cartzio</a></div>
                    <div
                        class="inline-block text-base text-slate-950 dark:text-white mx-0.5 ltr:rotate-0 rtl:rotate-180">
                        &rarr;</div>
                    <div class="inline-block uppercase text-[13px] font-bold text-orange-500" aria-current="page">Cart</div>
                </div>
            </div>
        </div>
    </section>
    <!-- Cart -->
    <section class="relative md:py-24 py-16" x-data="init_cart">
        <div class="container relative mx-auto px-3">
            <div class="grid lg:grid-cols-1">
                <div class="relative overflow-x-auto shadow dark:shadow-gray-800 rounded-md">
                    <table class="w-full text-start">
                        <thead class="text-sm uppercase bg-slate-50 dark:bg-slate-800">
                            <tr>
                                <th scope="col" class="p-4 w-4"></th>
                                <th scope="col" class="text-start p-4 min-w-[220px]">Product</th>
                                <th scope="col" class="p-4 w-24 min-w-[100px]">Price</th>
                                <th scope="col" class="p-4 w-56 min-w-[220px]">Qty</th>
                                <th scope="col" class="p-4 w-24 min-w-[100px]">Total($)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <template x-for="item in $store.cart.cart_items" :key="item.id">
                                <tr class="bg-white dark:bg-slate-900 border-t border-gray-100 dark:border-gray-800">
                                    <td class="p-4 pr-0">
                                        <div class="text-red-600 size-6" @click="$store.cart.updateQuantity(item.id, 0)">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                                                <path fill="currentColor"
                                                    d="M6.4 19L5 17.6l5.6-5.6L5 6.4L6.4 5l5.6 5.6L17.6 5L19 6.4L13.4 12l5.6 5.6l-1.4 1.4l-5.6-5.6z" />
                                            </svg>
                                        </div>
                                    </td>
                                    <td class="p-4">
                                        <span class="flex items-center">
                                            <img :src="item.image" class="rounded shadow dark:shadow-gray-800 w-12" alt="">
                                        <span class="ms-3">
                                        <span class="block font-semibold" x-text="item.name + ' (' + item.size + ')'"></span>
                                        </span></span>
                                    </td>
                                    <td class="p-4 text-center" x-text="'$ ' + item.price"></td>
                                    <td class="p-4 text-center">
                                        <div>
                                            <button class="size-9 inline-flex items-center justify-center tracking-wide align-middle text-base text-center rounded-md bg-orange-500/5 hover:bg-orange-500 text-orange-500 hover:text-white minus" @click="$store.cart.updateQuantity(item.id, item.quantity - 1)">-</button>
                                            <input min="0" name="quantity" type="number" readonly="" class="h-9 inline-flex items-center justify-center tracking-wide align-middle text-base text-center rounded-md bg-orange-500/5 hover:bg-orange-500 text-orange-500 hover:text-white pointer-events-none w-16 ps-4 quantity mx-1" :value="item.quantity">
                                            <button class="size-9 inline-flex items-center justify-center tracking-wide align-middle text-base text-center rounded-md bg-orange-500/5 hover:bg-orange-500 text-orange-500 hover:text-white plus" @click="$store.cart.updateQuantity(item.id, item.quantity + 1)">+</button>
                                        </div>
                                    </td>
                                    <td class="p-4 text-end" x-text="'$ ' + $store.cart.total"></td>
                                </tr>
                            </template>
                            
                        </tbody>
                    </table>
                </div>
                <div class="grid lg:grid-cols-12 md:grid-cols-2 grid-cols-1 mt-6 gap-6">
                    <div class="lg:col-span-9 md:order-1 order-3">
                        <div class="space-x-1">
                            <a class="py-2 px-5 inline-block font-semibold tracking-wide align-middle text-base text-center bg-orange-500 text-white rounded-md mt-2" href="{{ url_for('app.shop') }}">Shop Now</a>
                            <a class="py-2 px-5 inline-block font-semibold tracking-wide align-middle text-base text-center rounded-md bg-orange-500/5 hover:bg-orange-500 text-orange-500 hover:text-white mt-2" href="{{ url_for('app.checkout') }}">Checkout</a>
                        </div>
                    </div>
                    <div class="lg:col-span-3 md:order-2 order-1">
                        <ul class="list-none shadow dark:shadow-gray-800 rounded-md">
                            <li class="flex justify-between p-4">
                                <span class="font-semibold text-lg">Subtotal:</span>
                                <span class="text-slate-400">$ 1500</span></li>
                            <li class="flex justify-between p-4 border-t border-gray-100 dark:border-gray-800">
                                <span class="font-semibold text-lg">Taxes:</span>
                                <span class="text-slate-400">$ 150</span>
                            </li>
                            <li class="flex justify-between font-semibold p-4 border-t border-gray-200 dark:border-gray-600">
                                <span class="font-semibold text-lg">Total:</span>
                                <span class="font-semibold" x-text="$store.cart.total">$ 1650</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        
    </section>


<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('init_cart', () => ({
            init() {
                Alpine.store('cart').syncCart(JSON.parse('{{ cart | tojson | safe }}'))
            }
        }))
    })
</script>

</section>
{% endblock %}

project/app/templates/app/payment.html
{% extends 'app/account.html' %}
{% block content2 %}
<div class="w-full md:px-3 mt-6 md:mt-0">
    <h5 class="text-lg font-semibold mb-6">My Payments</h5>
    <div class="relative overflow-x-auto shadow dark:shadow-gray-800 rounded-md">
        <table class="w-full text-start text-slate-500 dark:text-slate-400">
            <thead class="text-sm uppercase bg-slate-50 dark:bg-slate-800">
                <tr class="text-start">
                    <th scope="col" class="px-2 py-3 text-start">Order no.</th>
                    <th scope="col" class="px-2 py-3 text-start">Date</th>
                    <th scope="col" class="px-2 py-3 text-start">Status</th>
                    <th scope="col" class="px-2 py-3 text-start">Total</th>
                    <th scope="col" class="px-2 py-3 text-start">Transaction ID</th>
                </tr>
            </thead>
            <tbody>
                {% for payment in payments %}
                <tr class="bg-white dark:bg-slate-900 text-start">
                    <th class="px-2 py-3 text-start" scope="row">{{ payment.order_id }}</th>
                    <td class="px-2 py-3 text-start">{{ payment.date }}</td>
                    <td class="px-2 py-3 text-start text-slate-400">{{ payment.payment_status }}</td>
                    <td class="px-2 py-3 text-start">$ {{ payment.amount_paid }}</td>
                    <td class="px-2 py-3 text-start">{{ payment.transaction_id }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

project/app/templates/app/signin.html
<!doctype html>
<html lang="en">

<head>
    <!-- Meta tags  -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />

    <title>Lavender - Sign In</title>
    <link rel="stylesheet" href="{{ url_for('app.static', filename='app/css/style.css') }}">

</head>
<body x-data class="is-header-blur">
    {% set messages = get_flashed_messages() %}
    <!-- wrapper -->
    <div class="min-h-screen flex grow bg-slate-50 dark:bg-gray-900">
        <main class="grid w-full grow grid-cols-1 place-items-center">
            <div class="w-full max-w-[26rem] p-4 sm:px-5">
                <div class="text-center">
                    <h2 class="text-3xl font-bold text-slate-600 dark:text-gray-100">Lavender</h2>
                    <div class="mt-4">
                        <h2 class="text-2xl font-semibold text-slate-600 dark:text-gray-100">Welcome Back</h2>
                        <p class="text-slate-400 dark:text-gray-300">Please sign in to continue</p>
                    </div>
                </div>
                <form action="" method="post">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                    <div class="card mt-5 rounded-lg p-5 lg:p-7">
                        <label class="block">
                            <span>Email:</span>
                            <span class="relative mt-1.5 flex">
                                <input class="form-input peer w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 pl-9 placeholder:text-slate-400/70 hover:border-slate-400 focus:border-primary dark:border-gray-450 dark:hover:border-gray-400 dark:focus:border-accent" placeholder="Enter Email" type="text" name="email">
                                <span class="pointer-events-none absolute flex h-full w-10 items-center justify-center text-slate-400 peer-focus:text-primary dark:text-gray-300  dark:peer-focus:text-accent">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="size-5 transition-colors duration-200" fill="none"viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z">
                                        </path>
                                    </svg>
                                </span>
                            </span>
                            {% for message in messages %}
                                {% if message['email'] %}
                                <p class="text-red-600 text-sm mt-1">{{ message['email'] }}</p>
                                {% endif %}
                            {% endfor %}
                        </label>
                        <label class="block">
                            <span>Password:</span>
                            <span class="relative mt-1.5 flex">
                                <input class="form-input peer w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 pl-9 placeholder:text-slate-400/70 hover:border-slate-400 focus:border-primary dark:border-gray-450 dark:hover:border-gray-400 dark:focus:border-accent" placeholder="Enter Username" type="password" name="password">
                                <span class="pointer-events-none absolute flex h-full w-10 items-center justify-center text-slate-400 peer-focus:text-primary dark:text-gray-300  dark:peer-focus:text-accent">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="size-5 transition-colors duration-200" fill="none" viewBox="0 0 24 24"
                                        stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                                    </svg>
                                </span>
                            </span>
                            {% for message in messages %}
                                {% if message['password'] %}
                                <p class="text-red-600 text-sm mt-1">{{ message['password'] }}</p>
                                {% endif %}
                            {% endfor %}
                        </label>
                        <div class="mt-4 flex items-center justify-between space-x-2">
                            <label class="inline-flex items-center space-x-2">
                                <input class="form-checkbox is-basic size-5 rounded border-slate-400/70 checked:border-primary checked:bg-primary hover:border-primary focus:border-primary dark:border-navy-400 dark:checked:border-accent dark:checked:bg-accent dark:hover:border-accent dark:focus:border-accent" type="checkbox" name="remember-me">
                                <span class="line-clamp-1">Remember me</span>
                            </label>
                            <a href="#" class="text-xs text-slate-400 transition-colors line-clamp-1 hover:text-slate-800 focus:text-slate-800 dark:text-navy-300 dark:hover:text-navy-100 dark:focus:text-navy-100">Forgot Password?</a>
                        </div>
                        <button class="btn mt-5 w-full bg-primary font-medium text-white hover:bg-primary-focus focus:bg-primary-focus active:bg-primary-focus/90 dark:bg-accent dark:hover:bg-accent-focus dark:focus:bg-accent-focus dark:active:bg-accent/90" type="submit">Sign In</button>
                        <div class="mt-4 text-center text-xs">
                            <p class="line-clamp-1">
                                <span>Dont have Account?</span>
                                <a class="text-primary transition-colors hover:text-primary-focus dark:text-accent-light dark:hover:text-accent" href="{{ url_for('app.signup') }}">Create account</a>
                            </p>
                        </div>
                    </div>
                </form>
            </div>
        </main>
    </div>
</body>
</html>